### GET request to example server
POST http://localhost:8080/
Content-Type: application/json

{
  "endgame": "HSR Mission",
  "version": 4.5,
  "side": 1,
  "stars": 3,
  "score": 12000,
  "zeroCycle": false,
  "notes": "First clear",
  "members": [
    { "name": "Bronya", "eidolon": 2, "signature": 5 },
    { "name": "Himeko", "eidolon": 1, "signature": 4 },
    { "name": "Himeko", "eidolon": 1, "signature": 4 },
    { "name": "Himeko", "eidolon": 1, "signature": 4 }
  ]
}

###