spring.datasource.url=jdbc:mysql://endgame_clears_hsr_missionits:1feb997f64ce761e2ed29fefa534ffb009233f19@ik-vkc.h.filess.io:61001/endgame_clears_hsr_missionits
spring.datasource.username=endgame_clears_hsr_missionits
spring.datasource.password=1feb997f64ce761e2ed29fefa534ffb009233f19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true